version: '3.4'

networks:
  tcc-network:
    name: tcc-network
    external: false

services:
  backend:
    extends:
      file: Backend/src/Api/docker-compose.yml
      service: backend
    depends_on:
      - database

  frontend:
    extends:
      file: FrontEnd/docker-compose.yml
      service: frontend
    depends_on:
      - backend
  
  database:
    extends:
      file: Database/docker-compose.sqlserver-arm.yml
      service: sql-server
