version: '3.4'

networks:
  tcc-network:
    name: tcc-network
    external: false

services:
  my-sql-server:
    image: arm64v8/mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=@BcD1234
    networks:
      - tcc-network