version: '3.4'

services:
  sql-server:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Abcd!234
      - MSSQL_PID=Developer
      - MSSQL_USER=sa