version: '3.4'

networks:
  tcc-network:
    name: tcc-network
    external: true

services:
  backend:
    build:
      context: ../..
      dockerfile: src/Api/Dockerfile
    image: backend
    ports:
      - '7248:443'
      - '5248:80'
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+;http://+
      ASPNETCORE_Kestrel:Certificates:Default:Password: ABC@abc123
      ASPNETCORE_Kestrel:Certificates:Default:Path: /https/aspnetapp.pfx
      ConnectionStrings:Default: Server=unasp-ht-engenhara-tcc.database.windows.net,1433;Initial Catalog=tcc;Persist Security Info=False;User ID=admin.tcc;Password=XMyqq6NvdML4dfERfu;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
    volumes:
      - ~/.aspnet/https:/https:ro
    # depends_on:
    #   - database
    networks:
      - tcc-network


  # database:
  #   extends:
  #     file: ../../../Database/docker-compose.sqlserver-arm.yml.yml
  #     service: sqlserver
