version: '3.4'

networks:
  tcc-network:
    name: tcc-network
    external: false

services:
  backend:
    build:
      context: ../..
      dockerfile: src/Api/Dockerfile
    image: backend
    ports:
      - '7248:443'
      - '5248:80'
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+;http://+
      ASPNETCORE_Kestrel:Certificates:Default:Password: ABC@abc123
      ASPNETCORE_Kestrel:Certificates:Default:Path: /https/aspnetapp.pfx
      ConnectionStrings:MySql: server=host.docker.internal,3306;database=tcc;user=root;password=@BcD1234
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - database
    networks:
      - tcc-network


  database:
    extends:
      file: ../../../Database/docker-compose.mysql.yml
      service: my-sql-server
